In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
patients = pd.read_csv('./IndividualDetails.csv')
patients['current_status'].value_counts()

current_status
Hospitalized    8301
Recovered        139
Deceased          30
Migrated           1
Name: count, dtype: int64

In [3]:
total = patients.shape[0]

In [4]:
hospitalized = patients[patients['current_status'] == 'Hospitalized'].shape[0]
recovered = patients[patients['current_status'] == 'Recovered'].shape[0]
deaths = patients[patients['current_status'] == 'Deceased'].shape[0]

In [5]:
patients_bar = patients['detected_state'].value_counts().reset_index()

In [6]:
patients_bar

                 detected_state  count
0                   Maharashtra   1761
1                         Delhi   1069
2                    Tamil Nadu    969
3                     Rajasthan    700
4                Madhya Pradesh    529
5                     Telangana    503
6                       Gujarat    468
7                 Uttar Pradesh    452
8                Andhra Pradesh    405
9                        Kerala    373
10                    Karnataka    226
11            Jammu and Kashmir    224
12                      Haryana    179
13                       Punjab    158
14                  West Bengal    134
15                        Bihar     64
16                       Odisha     54
17                  Uttarakhand     35
18             Himachal Pradesh     32
19                        Assam     29
20                 Chhattisgarh     25
21                   Chandigarh     19
22                    Jharkhand     17
23                       Ladakh     15
24  Andaman and Nicobar Islands     11
25                   Puducherry      7
26                          Goa      7
27                      Manipur      2
28                      Tripura      2
29                      Mizoram      1
30            Arunachal Pradesh      1
31       Dadra and Nagar Haveli      1

In [7]:
n_patients = patients[patients['current_status'] == 'Recovered']
patients_bar = n_patients['detected_state'].value_counts().reset_index()